//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Z_Financial_CRM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EgitimKampi_Financial_CRM_dbEntities : DbContext
    {
        public EgitimKampi_Financial_CRM_dbEntities()
            : base("name=EgitimKampi_Financial_CRM_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<BankProcess> BankProcesses { get; set; }
        public virtual DbSet<Bank> Banks { get; set; }
        public virtual DbSet<Bill> Bills { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Spending> Spendings { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
